{"uuid": "a28f8ce0-2d01-43af-9c79-ef7c23ad45ae", "children": ["b0d1633b-a7fc-4deb-9758-e79b5f66b326"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "TypeError: get_verify_number() missing 1 required positional argument: 'file_path'\n", "trace": "  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 12, in with_login_cpc\n    verify_number = cpclogin.get_verify_number()\n"}, "start": 1568472709086, "stop": 1568472711278}], "start": 1568472709086, "stop": 1568472711310}