{"uuid": "aed80ce0-d5db-491d-a85b-e30c7ca9d98f", "children": ["8f55192a-db56-423a-b042-c20f414670b0"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "TypeError: get_verify_number() missing 1 required positional argument: 'file_path'\n", "trace": "  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 12, in with_login_cpc\n    verify_number = cpclogin.get_verify_number()\n"}, "start": 1568472721718, "stop": 1568472723852}], "start": 1568472721718, "stop": 1568472723859}